update release

diff --git a/script/release b/script/release
--- a/script/release
+++ b/script/release
@@ -1,28 +1,75 @@
 #!/bin/sh
+#/ script/release creates a new release. It is run by GitHub Actions on push to main.
 
-set -ex
+set -e
 
-SCRIPT_DIR="$(CDPATH="" cd -- "$(dirname -- "$0")" && pwd)"
+CDPATH="" cd -- "$(dirname -- "$0")/.."
 
-CDPATH="" cd -- "$SCRIPT_DIR/.."
+if [ -f ".no-release" ]; then {
+  echo "Release disabled by .no-release file"
+  exit 0
+}; fi
 
 [ -n "$GITHUB_TOKEN" ] || {
   echo GITHUB_TOKEN must be set
   exit 1
 }
 
-. script/goenv
+if [ "$(git rev-parse --is-shallow-repository)" != "false" ]; then
+  echo "script/release cannot be run on a shallow clone"
+  exit 1
+fi
 
-make -s bin/goreleaser bin/semver-next bin/jq bin/build-bootstrapper bin/gh
-
-GITHUB_SHA="${GITHUB_SHA:-"$(git rev-parse HEAD)"}"
-GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-"WillAbides/bindown"}"
-
-bin/semver-next "$GITHUB_REPOSITORY" -r "$GITHUB_SHA" --create-tag --require-labels
+script/bindown -q install semver-next
+script/bindown -q install semver-prev
+script/bindown -q install gh
+script/bindown -q install jq
 
 git fetch --tags
 
-bin/goreleaser release
-TAG="$(bin/jq -r '.tag' dist/metadata.json)"
-bin/build-bootstrapper -tag "$TAG" > bootstrap-bindown.sh
-bin/gh release upload "$TAG" bootstrap-bindown.sh
+GITHUB_SHA="${GITHUB_SHA:-"$(git rev-parse HEAD)"}"
+GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-"WillAbides/goproject-tmpl"}"
+
+PREV_REF="$(bin/semver-prev --prefix v --fallback "" --ref "$GITHUB_SHA")"
+PREV_VERSION="$PREV_REF"
+if [ -z "$PREV_REF" ]; then
+  PREV_REF="$(git rev-list --max-parents=0 HEAD)"
+  PREV_VERSION="0.0.0"
+fi
+
+RES="$(bin/semver-next "$GITHUB_REPOSITORY" -r "$GITHUB_SHA" -p "$PREV_REF" -v "$PREV_VERSION" --json)"
+NEXT_VERSION="$(echo "$RES" | bin/jq -r .next_version)"
+CHANGE_LEVEL="$(echo "$RES" | bin/jq -r .change_level)"
+
+if [ "$CHANGE_LEVEL" = "no change" ]; then
+  echo "No changes since last release"
+  exit 0
+fi
+
+MODULE_NAME="$(go list -m)"
+MAJOR_VERSION="$(echo "$NEXT_VERSION" | cut -d. -f1)"
+MODULE_VERSION_SUFFIX="$(echo "$MODULE_NAME" | grep -o '/v[0-9][0-9]*$' || true)"
+
+# If MAJOR_VERSION >= 2, make sure the module name ends with `/v$MAJOR_VERSION`
+if [ "$MAJOR_VERSION" -ge 2 ]; then
+  if [ "$MODULE_VERSION_SUFFIX" != "/v$MAJOR_VERSION" ]; then
+    echo "Module name must end with /v$MAJOR_VERSION"
+    exit 1
+  fi
+else
+  if [ -n "$MODULE_VERSION_SUFFIX" ]; then
+    echo "Module name must not end with /v[0-9][0-9]*"
+    exit 1
+  fi
+fi
+
+bin/gh release create "v$NEXT_VERSION" -t "v$NEXT_VERSION" --generate-notes
+
+# If there's no .goreleaser.yaml, there's nothing left to do.
+[ -f ".goreleaser.yaml" ] || exit 0
+
+git fetch --tags
+
+script/bindown -q install goreleaser
+
+bin/goreleaser release --clean
